### ISSUE TITLE
Script stops after a while

### ISSUE THREAD

**Issue by ryanwalexander** [tillsc/can2mqtt#1]
Hi there, this script works great, thank you for creating it.  

I'm encountering an issue when it runs for a while but I'm having difficulty finding the cause or coming up with a fix.  The MQTT broker & CAN connections do not present issues with any of the other connections to them.

Is it straightforward to detect if the script stops working and if it does to restart it?  I'm a bit new at this so don't know a sensible way to do this.

Sometimes the script stops with a traceback as shown below, and other times there is no traceback but it stops bridging the messages to MQTT.

![image](https://user-images.githubusercontent.com/9535302/141315585-5a36b3e4-09c7-47e4-af2c-d1357818f6d1.png)

**Comment by ryanwalexander** [comment]
@tillsc any ideas?

**Comment by tillsc** [comment]
I'm running can2mqtt via system.d. This restarts the service for me when something happenes. So I just programmed the stuff to fail fast and let system.d care about the rest.

**Comment by tillsc** [comment]
I pasted my script here: https://gist.github.com/tillsc/d2c6b134b7eb4ab52317fc4dc8fb814c (from `/etc/systemd/system/can2mqtt.service` in Raspbian 10)
